In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import scipy.stats as st

# CHECKPOINT-1 Data Understanding And Cleaning

In [2]:
#First we Read the file

In [3]:
companies=pd.read_csv(r'C:\Users\DELL\Desktop\data science training\Spark Funds Industrial Assignment - 1\Spark Funds Industrial Assignment - 1\companies.txt',encoding="ISO-8859-1",delimiter="\t")
rounds2=pd.read_csv(r'C:\Users\DELL\Desktop\data science training\Spark Funds Industrial Assignment - 1\Spark Funds Industrial Assignment - 1\rounds2.csv',encoding="ISO-8859-1")

In [4]:
companies.columns                   #Columns Present in companies dataframe

Index(['permalink', 'name', 'homepage_url', 'category_list', 'status',
       'country_code', 'state_code', 'region', 'city', 'founded_at'],
      dtype='object')

In [5]:
companies['permalink'].unique()          # To unique values in the column

array(['/Organization/-Fame', '/Organization/-Qounter',
       '/Organization/-The-One-Of-Them-Inc-', ...,
       '/Organization/Ã\x81Eron', '/Organization/Ã\x94Asys-2',
       '/Organization/Ä°Novatiff-Reklam-Ve-Tanä±Tä±M-Hizmetleri-Tic'],
      dtype=object)

In [6]:
companies.head(50)

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/Organization/-Fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/Organization/-Qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/Organization/-The-One-Of-Them-Inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/Organization/0-6-Com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/Organization/004-Technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010
5,/Organization/01Games-Technology,01Games Technology,http://www.01games.hk/,Games,operating,HKG,NaN,Hong Kong,Hong Kong,NaN
6,/Organization/0Ndine-Biomedical-Inc,Ondine Biomedical Inc.,http://ondinebio.com,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,01-01-1997
7,/Organization/0Xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
8,/Organization/1,One Inc.,http://whatis1.com,Mobile,operating,USA,CA,SF Bay Area,San Francisco,01-08-2011
9,/Organization/1-2-3-Listo,"1,2,3 Listo",http://www.123listo.com,E-Commerce,operating,CHL,12,Santiago,Las Condes,01-01-2012
10,/Organization/1-4-All,1-4 All,NaN,Entertainment|Games|Software,operating,USA,NC,NC - Other,Connellys Springs,NaN
11,/Organization/1-618-Technology,1.618 Technology,http://www.Homeandcondogallery.com,Networking|Real Estate|Web Hosting,operating,USA,FL,Orlando,Orlando,07-12-2013
12,/Organization/1-800-Dentist,1-800-DENTIST,http://www.1800dentist.com,Health and Wellness,operating,USA,CA,Los Angeles,Los Angeles,01-01-1986
13,/Organization/1-800-Doctors,1-800-DOCTORS,http://1800doctors.com,Health and Wellness,operating,USA,NJ,Newark,Iselin,01-01-1984
14,/Organization/1-800-Publicrelations-Inc-,"1-800-PublicRelations, Inc.",http://www.1800publicrelations.com,Internet Marketing|Media|Public Relations,operating,USA,NY,New York City,New York,24-10-2013
15,/Organization/1-Mainstream,1 Mainstream,http://www.1mainstream.com,Apps|Cable|Distribution|Software,acquired,USA,CA,SF Bay Area,Cupertino,01-03-2012
16,/Organization/1-Of-99,1 of 99,NaN,Entertainment|Games,operating,USA,CA,SF Bay Area,Mountain View,01-12-2014
17,/Organization/10-20-Media,10-20 Media,http://www.10-20media.com,E-Commerce,operating,USA,MD,Baltimore,Woodbine,01-01-2001
18,/Organization/10-Minutes-With,10 Minutes With,http://10minuteswith.com,Education,operating,GBR,H9,London,London,01-01-2013
19,/Organization/1000-Corks,1000 Corks,http://1000corks.com,Search,operating,USA,OR,"Portland, Oregon",Lake Oswego,01-01-2008
20,/Organization/1000-Markets,1000 Markets,http://www.1000markets.com,Art|E-Commerce|Marketplaces,acquired,USA,WA,Seattle,Seattle,01-01-2009
21,/Organization/1000Chi,Beijing 1000CHI Software Technology,http://www.1000chi.com/,Mobile,operating,NaN,NaN,NaN,NaN,01-01-2008
22,/Organization/1000Lookz,1000Lookz,http://1000lookz.com,Beauty,operating,IND,25,Chennai,Chennai,01-01-2008
23,/Organization/1000Memories,1000memories,http://1000memories.com,Curated Web,acquired,USA,CA,SF Bay Area,San Francisco,01-07-2010
24,/Organization/1000Museums-Com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008
25,/Organization/1001-Menus,ZenChef,http://zenchef.com/en/,Local Businesses|Restaurants,operating,FRA,A8,Paris,Paris,20-11-2010
26,/Organization/1001Pharmacies-Com,1001pharmacies.com,http://www.1001pharmacies.com/,Cosmetics|Marketplaces,operating,FRA,A9,Montpellier,Montpellier,01-01-2012
27,/Organization/1006-Tv,1006.tv,http://www.1006.tv/,Games|Media,operating,CHN,22,Beijing,Beijing,01-01-2009
28,/Organization/100Du-Tv,100du.tv,http://www.100du.com,Hospitality,operating,CHN,23,Shanghai,Shanghai,NaN
29,/Organization/100E-Com,100e.com,http://www.100e.com,Education,operating,CHN,22,Beijing,Beijing,NaN
30,/Organization/100Health,Redox,http://www.redoxengine.com,Health Care|Health Care Information Technology...,operating,USA,WI,Madison,Madison,04-07-2014
31,/Organization/100Plus,100Plus,http://www.100plus.com,Analytics,acquired,USA,CA,SF Bay Area,San Francisco,16-09-2011
32,/Organization/1010Data,1010data,http://www.1010data.com,Software,acquired,USA,NY,New York City,New York,01-01-2000
33,/Organization/10Alike,Cliptone,http://www.cliptone.me/,Advertising|Image Recognition|Sales and Market...,operating,CAN,ON,Toronto,Toronto,03-03-2012
34,/Organization/10Bestthings,10BestThings,http://10bestthings.com,Curated Web,closed,USA,OH,Cleveland,Cleveland,01-04-2009
35,/Organization/10K-2,Beans Around,http://beansaround.com/,Coffee|Delivery|Subscription Service,operating,NaN,NaN,NaN,NaN,01-04-2015
36,/Organization/10Sec,10sec,https://10s.ec/,E-Commerce|Mobile Commerce|Social Commerce,operating,USA,CA,SF Bay Area,San Francisco,08-07-2013
37,/Organization/10Seconds-Software,10seconds Software,http://www.10secondsSoftware.com,Enterprise Software|Mobility|Software,operating,AUS,2,Sydney,Sydney,01-07-2009
38,/Organization/10Six,10Six,http://10sixenergy.com,Batteries|Electronics|Energy,operating,USA,NY,New York City,New York,NaN
39,/Organization/10Tracks-2,10tracks,http://10tracks.com,iOS|Mobile|Music,operating,NaN,NaN,NaN,NaN,01-01-2012
40,/Organization/10X-Genomics,10X Genomics,http://10xgenomics.com,Biotechnology|Technology,operating,USA,CA,SF Bay Area,Pleasanton,01-01-2012
41,/Organization/10X-Technologies,10X Technologies,http://10xtechnologies.com,Biotechnology,operating,USA,CA,SF Bay Area,Oakland,01-01-2012
42,/Organization/10X10-Room,10X10 Room,http://10x10room.com,Software,operating,USA,MA,Boston,Lexington,01-01-2010
43,/Organization/10Â°North,10Â°North,NaN,Fashion,operating,CAN,ON,Toronto,Mississauga,05-01-2013
44,/Organization/11-Health,11 Health,http://www.11health.com,Health and Wellness,operating,GBR,H9,London,London,NaN
45,/Organization/115-Network-Disks,115 network disks,http://www.115.com/,EdTech|Education,operating,NaN,NaN,NaN,NaN,NaN
46,/Organization/117Go,117go,http://117go.com,Social Travel,operating,CHN,23,Shanghai,Shanghai,01-10-2011
47,/Organization/11I-Solutions,11i Solutions,http://www.11isolutions.com,Enterprise Software,closed,USA,AL,Huntsville,Huntsville,NaN
48,/Organization/12-Labs,12 Labs,http://www.getapplause.com/,Health and Wellness|Personal Health,operating,USA,CA,SF Bay Area,Palo Alto,01-08-2014
49,/Organization/12-Star-Survival,12 Star Survival,http://www.12starsurvival.com,Sports,operating,DNK,21,DNK - Other,Vinding,17-07-2013

In [7]:
rounds2.columns                             #columns present in rounds2 dataframe

Index(['company_permalink', 'funding_round_permalink', 'funding_round_type',
       'funding_round_code', 'funded_at', 'raised_amount_usd'],
      dtype='object')

In [8]:
rounds2.head(2)

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/ORGANIZATION/-QOUNTER,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN

In [9]:
rounds2['company_permalink'].unique()                      #To find the unique values in the column

array(['/organization/-fame', '/ORGANIZATION/-QOUNTER',
       '/organization/-qounter', ..., '/organization/ã\x81eron',
       '/ORGANIZATION/Ã\x94ASYS-2',
       '/organization/ä°novatiff-reklam-ve-tanä±tä±m-hizmetleri-tic'],
      dtype=object)

In [10]:
#As we seen above thatcompanies['permalink']column contains some symbols which are not readable so we have to convert it in to readable form. 
companies['permalink'] = companies['permalink'].apply(lambda x:x.encode('utf-8').decode('ascii','ignore'))

In [11]:
companies['permalink'].tail()

66363    /Organization/Zznode-Science-And-Technology-Co...
66364                            /Organization/Zzzzapp-Com
66365                                   /Organization/Eron
66366                                 /Organization/Asys-2
66367    /Organization/Novatiff-Reklam-Ve-TanTM-Hizmetl...
Name: permalink, dtype: object

In [12]:
companies.tail()

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
66363,/Organization/Zznode-Science-And-Technology-Co...,ZZNode Science and Technology,http://www.zznode.com,Enterprise Software,operating,CHN,22,Beijing,Beijing,NaN
66364,/Organization/Zzzzapp-Com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
66365,/Organization/Eron,ÃERON,http://www.aeron.hu/,NaN,operating,NaN,NaN,NaN,NaN,01-01-2011
66366,/Organization/Asys-2,Ãasys,http://www.oasys.io/,Consumer Electronics|Internet of Things|Teleco...,operating,USA,CA,SF Bay Area,San Francisco,01-01-2014
66367,/Organization/Novatiff-Reklam-Ve-TanTM-Hizmetl...,Ä°novatiff Reklam ve TanÄ±tÄ±m Hizmetleri Tic,http://inovatiff.com,Consumer Goods|E-Commerce|Internet,operating,NaN,NaN,NaN,NaN,NaN

In [13]:
#As we seen above that rounds['company_permalink']column contains some symbols which are not readable so we have to convert it in to readable form. 
rounds2['company_permalink'] = rounds2['company_permalink'].apply(lambda x:x.encode('utf-8').decode('ascii','ignore'))

In [14]:
#to covert the rounds2['company_permalink'] column elemnets in lower for cleaning purpose.
rounds2['company_permalink']=rounds2['company_permalink'].apply(lambda x:x.lower())

In [15]:
rounds2['company_permalink'].unique()

array(['/organization/-fame', '/organization/-qounter',
       '/organization/-the-one-of-them-inc-', ..., '/organization/eron',
       '/organization/asys-2',
       '/organization/novatiff-reklam-ve-tantm-hizmetleri-tic'],
      dtype=object)

In [16]:
rounds2.tail()

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
114944,/organization/zzzzapp-com,/funding-round/8f6d25b8ee4199e586484d817bceda05,convertible_note,NaN,01-03-2014,41313.0
114945,/organization/zzzzapp-com,/funding-round/ff1aa06ed5da186c84f101549035d4ae,seed,NaN,01-05-2013,32842.0
114946,/organization/eron,/funding-round/59f4dce44723b794f21ded3daed6e4fe,venture,A,01-08-2014,NaN
114947,/organization/asys-2,/funding-round/35f09d0794651719b02bbfd859ba9ff5,seed,NaN,01-01-2015,18192.0
114948,/organization/novatiff-reklam-ve-tantm-hizmetl...,/funding-round/af942869878d2cd788ef5189b435ebc4,grant,NaN,01-10-2013,14851.0

In [17]:
rounds2['company_permalink'].value_counts()

/organization/solarflare            19
/organization/exagen-diagnostics    18
/organization/semprius              18
/organization/quellan               18
/organization/vocalocity            17
                                    ..
/organization/better-living-yoga     1
/organization/kare-partners          1
/organization/moonbasa               1
/organization/siliconstor            1
/organization/extratkt               1
Name: company_permalink, Length: 66368, dtype: int64

In [18]:
len(rounds2['company_permalink'].unique())

66368

In [19]:
df3=~(np.intersect1d(companies['permalink'],rounds2['company_permalink']))

In [20]:
df3

array([], dtype=object)

In [21]:
#Since intersection Array is empty means there are no companies in the rounds2 file which are not  present in companies .

In [22]:
#To covert the companies['permalink'] column elemnets in lower for cleaning purpose.
companies['permalink']=companies['permalink'].apply(lambda x:x.lower())

# Merging of two dataframes

In [23]:
master_frame1=pd.merge(rounds2,companies,left_on='company_permalink',right_on='permalink')

In [24]:
master_frame1.head(50)

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0,/organization/-fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/organization/-qounter,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN,/organization/-qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0,/organization/-qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
3,/organization/-the-one-of-them-inc-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0,/organization/-the-one-of-them-inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0,/organization/0-6-com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
5,/organization/004-technologies,/funding-round/1278dd4e6a37fa4b7d7e06c21b3c1830,venture,NaN,24-07-2014,NaN,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010
6,/organization/01games-technology,/funding-round/7d53696f2b4f607a2f2a8cbb83d01839,undisclosed,NaN,01-07-2014,41250.0,/organization/01games-technology,01Games Technology,http://www.01games.hk/,Games,operating,HKG,NaN,Hong Kong,Hong Kong,NaN
7,/organization/0ndine-biomedical-inc,/funding-round/2b9d3ac293d5cdccbecff5c8cb0f327d,seed,NaN,11-09-2009,43360.0,/organization/0ndine-biomedical-inc,Ondine Biomedical Inc.,http://ondinebio.com,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,01-01-1997
8,/organization/0ndine-biomedical-inc,/funding-round/954b9499724b946ad8c396a57a5f3b72,venture,NaN,21-12-2009,719491.0,/organization/0ndine-biomedical-inc,Ondine Biomedical Inc.,http://ondinebio.com,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,01-01-1997
9,/organization/0xdata,/funding-round/383a9bd2c04f7038bb543ccef5ba3eae,seed,NaN,22-05-2013,3000000.0,/organization/0xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
10,/organization/0xdata,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,B,09-11-2015,20000000.0,/organization/0xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
11,/organization/0xdata,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,NaN,03-01-2013,1700000.0,/organization/0xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
12,/organization/0xdata,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,A,19-07-2014,8900000.0,/organization/0xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
13,/organization/1,/funding-round/03b975068632eba5bfdb937ec8c07a68,seed,NaN,05-02-2014,150000.0,/organization/1,One Inc.,http://whatis1.com,Mobile,operating,USA,CA,SF Bay Area,San Francisco,01-08-2011
14,/organization/1,/funding-round/5de6d8828aef7d925d97918d15727670,undisclosed,NaN,05-02-2013,NaN,/organization/1,One Inc.,http://whatis1.com,Mobile,operating,USA,CA,SF Bay Area,San Francisco,01-08-2011
15,/organization/1,/funding-round/e82464f22241715dd1a6c77241055ed1,seed,NaN,20-07-2011,1000050.0,/organization/1,One Inc.,http://whatis1.com,Mobile,operating,USA,CA,SF Bay Area,San Francisco,01-08-2011
16,/organization/1-2-3-listo,/funding-round/6de4609e894495105bc791ed64361288,seed,NaN,18-02-2013,40000.0,/organization/1-2-3-listo,"1,2,3 Listo",http://www.123listo.com,E-Commerce,operating,CHL,12,Santiago,Las Condes,01-01-2012
17,/organization/1-4-all,/funding-round/e97a192e13ea0ee3c4f71136b4f3ec16,equity_crowdfunding,NaN,21-04-2013,NaN,/organization/1-4-all,1-4 All,NaN,Entertainment|Games|Software,operating,USA,NC,NC - Other,Connellys Springs,NaN
18,/organization/1-618-technology,/funding-round/83b8f4c7d37ecef5e001a5e953bf461a,equity_crowdfunding,NaN,22-01-2014,NaN,/organization/1-618-technology,1.618 Technology,http://www.Homeandcondogallery.com,Networking|Real Estate|Web Hosting,operating,USA,FL,Orlando,Orlando,07-12-2013
19,/organization/1-800-dentist,/funding-round/5274aacc211163fc7c86539ce94bbacc,undisclosed,NaN,19-08-2010,NaN,/organization/1-800-dentist,1-800-DENTIST,http://www.1800dentist.com,Health and Wellness,operating,USA,CA,Los Angeles,Los Angeles,01-01-1986
20,/organization/1-800-doctors,/funding-round/9eb8c7790a0c200d79e75785d1c4aa12,convertible_note,NaN,02-03-2011,1750000.0,/organization/1-800-doctors,1-800-DOCTORS,http://1800doctors.com,Health and Wellness,operating,USA,NJ,Newark,Iselin,01-01-1984
21,/organization/1-800-publicrelations-inc-,/funding-round/11c228f58831bc7ed337ef69ecc560c2,private_equity,NaN,01-02-2015,6000000.0,/organization/1-800-publicrelations-inc-,"1-800-PublicRelations, Inc.",http://www.1800publicrelations.com,Internet Marketing|Media|Public Relations,operating,USA,NY,New York City,New York,24-10-2013
22,/organization/1-mainstream,/funding-round/b952cbaf401f310927430c97b68162ea,venture,NaN,17-03-2015,5000000.0,/organization/1-mainstream,1 Mainstream,http://www.1mainstream.com,Apps|Cable|Distribution|Software,acquired,USA,CA,SF Bay Area,Cupertino,01-03-2012
23,/organization/1-of-99,/funding-round/b5c811f561cfb5701cd5b1762120bbc3,convertible_note,NaN,13-12-2014,100000.0,/organization/1-of-99,1 of 99,NaN,Entertainment|Games,operating,USA,CA,SF Bay Area,Mountain View,01-12-2014
24,/organization/10-20-media,/funding-round/436874dc54b54460f99f44c06e50990a,debt_financing,NaN,11-01-2011,800000.0,/organization/10-20-media,10-20 Media,http://www.10-20media.com,E-Commerce,operating,USA,MD,Baltimore,Woodbine,01-01-2001
25,/organization/10-20-media,/funding-round/8025ee9c11a586eac4a234ddec7beb30,debt_financing,NaN,18-06-2009,500000.0,/organization/10-20-media,10-20 Media,http://www.10-20media.com,E-Commerce,operating,USA,MD,Baltimore,Woodbine,01-01-2001
26,/organization/10-20-media,/funding-round/a884bf8326b9fd59789c0f74a28dbc3b,debt_financing,NaN,28-12-2011,500000.0,/organization/10-20-media,10-20 Media,http://www.10-20media.com,E-Commerce,operating,USA,MD,Baltimore,Woodbine,01-01-2001
27,/organization/10-20-media,/funding-round/d205f5416ce55e126beda3ed2bf2c2cd,debt_financing,NaN,30-03-2010,250000.0,/organization/10-20-media,10-20 Media,http://www.10-20media.com,E-Commerce,operating,USA,MD,Baltimore,Woodbine,01-01-2001
28,/organization/10-minutes-with,/funding-round/0faccbbcc5818dc5326469f13f5a8ac8,venture,A,09-10-2014,4000000.0,/organization/10-minutes-with,10 Minutes With,http://10minuteswith.com,Education,operating,GBR,H9,London,London,01-01-2013
29,/organization/10-minutes-with,/funding-round/f245a74b4c54610ae843e17bdf4d1113,seed,NaN,01-01-2013,400000.0,/organization/10-minutes-with,10 Minutes With,http://10minuteswith.com,Education,operating,GBR,H9,London,London,01-01-2013
30,/organization/1000-corks,/funding-round/8f4fa70e24269ddd8bdf6658906b356b,seed,NaN,23-08-2011,40000.0,/organization/1000-corks,1000 Corks,http://1000corks.com,Search,operating,USA,OR,"Portland, Oregon",Lake Oswego,01-01-2008
31,/organization/1000-markets,/funding-round/ce6749b6441f52ccaf38b6d5578779fd,seed,NaN,15-05-2009,500000.0,/organization/1000-markets,1000 Markets,http://www.1000markets.com,Art|E-Commerce|Marketplaces,acquired,USA,WA,Seattle,Seattle,01-01-2009
32,/organization/1000chi,/funding-round/854fae13c5b26b2ea6b32b06c2e5890c,angel,NaN,01-04-2010,43923865.0,/organization/1000chi,Beijing 1000CHI Software Technology,http://www.1000chi.com/,Mobile,operating,NaN,NaN,NaN,NaN,01-01-2008
33,/organization/1000lookz,/funding-round/e07f6e580046d00c7aeb33fafb9d90a3,venture,NaN,22-07-2013,NaN,/organization/1000lookz,1000Lookz,http://1000lookz.com,Beauty,operating,IND,25,Chennai,Chennai,01-01-2008
34,/organization/1000memories,/funding-round/502bd0e50c27616995e4bdad24605ef8,venture,A,16-02-2011,2520000.0,/organization/1000memories,1000memories,http://1000memories.com,Curated Web,acquired,USA,CA,SF Bay Area,San Francisco,01-07-2010
35,/organization/1000memories,/funding-round/f5fb428ed1e63321f88b3e646ba85f00,seed,NaN,01-01-2010,15000.0,/organization/1000memories,1000memories,http://1000memories.com,Curated Web,acquired,USA,CA,SF Bay Area,San Francisco,01-07-2010
36,/organization/1000museums-com,/funding-round/01c1aa44619ae45a16e3098fc73facfa,debt_financing,NaN,08-04-2013,647879.0,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008
37,/organization/1000museums-com,/funding-round/0953b01a028ac4cd075415554cb363b4,debt_financing,NaN,19-09-2014,500000.0,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008
38,/organization/1000museums-com,/funding-round/13be128d655076a025221d7fddc90d68,venture,NaN,14-10-2009,265940.0,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008
39,/organization/1000museums-com,/funding-round/6aeb32ab3fc05db2b606d7a2466e8c09,venture,NaN,15-01-2014,2906832.0,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008
40,/organization/1000museums-com,/funding-round/6dcccfea326e6add866bf67aafb0a7df,convertible_note,NaN,01-12-2014,NaN,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008
41,/organization/1000museums-com,/funding-round/89317984885b44f02e4befb9dc2e588c,venture,NaN,01-08-2014,1500000.0,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008
42,/organization/1000museums-com,/funding-round/adf2f3272af9f552b87e01f10f0b9234,venture,NaN,01-02-2014,NaN,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008
43,/organization/1000museums-com,/funding-round/f8e256ceacabe73fa5d4c217f00f50b3,debt_financing,NaN,13-11-2015,332800.0,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008
44,/organization/1000museums-com,/funding-round/fd1b3064232ba9b3cfb5653a619e82e8,venture,NaN,05-04-2011,642000.0,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008
45,/organization/1001-menus,/funding-round/6364929e6f6c94921f9c853f53b10b7a,seed,NaN,15-12-2012,390000.0,/organization/1001-menus,ZenChef,http://zenchef.com/en/,Local Businesses|Restaurants,operating,FRA,A8,Paris,Paris,20-11-2010
46,/organization/1001-menus,/funding-round/645b4cd895450b8e0268027cd7813047,venture,B,04-11-2015,6602694.0,/organization/1001-menus,ZenChef,http://zenchef.com/en/,Local Businesses|Restaurants,operating,FRA,A8,Paris,Paris,20-11-2010
47,/organization/1001-menus,/funding-round/8025123b90c1ab687f9857ffe18bfd3b,venture,A,13-11-2013,1736910.0,/organization/1001-menus,ZenChef,http://zenchef.com/en/,Local Businesses|Restaurants,operating,FRA,A8,Paris,Paris,20-11-2010
48,/organization/1001-menus,/funding-round/9d6619bf66478dd8bf19bfc8dc237770,seed,NaN,27-12-2012,132169.0,/organization/1001-menus,ZenChef,http://zenchef.com/en/,Local Businesses|Restaurants,operating,FRA,A8,Paris,Paris,20-11-2010
49,/organization/1001-menus,/funding-round/b6c28ea4ebe32db7083052cf87e7c368,venture,A,25-10-2013,1800000.0,/organization/1001-menus,ZenChef,http://zenchef.com/en/,Local Businesses|Restaurants,operating,FRA,A8,Paris,Paris,20-11-2010

In [25]:
master_frame1.info()                       #To find the information about the merges dataframe-master_frame1

<class 'pandas.core.frame.DataFrame'>
Int64Index: 114949 entries, 0 to 114948
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   company_permalink        114949 non-null  object
 1   funding_round_permalink  114949 non-null  object
 2   funding_round_type       114949 non-null  object
 3   funding_round_code       31140 non-null   object
 4   funded_at                114949 non-null  object
 5   raised_amount_usd        94959 non-null   float64
 6   permalink                114949 non-null  object
 7   name                     114948 non-null  object
 8   homepage_url             108815 non-null  object
 9   category_list            111539 non-null  object
 10  status                   114949 non-null  object
 11  country_code             106271 non-null  object
 12  state_code               104003 non-null  object
 13  region                   104782 non-null  object
 14  city                     104785 non-null  object
 15  founded_at               94428 non-null   object
dtypes: float64(1), object(15)
memory usage: 14.9+ MB

In [26]:
round(100*((master_frame1.isnull().sum())/(len(master_frame1))),4)  #To find the percentage of null values in each column.

company_permalink           0.0000
funding_round_permalink     0.0000
funding_round_type          0.0000
funding_round_code         72.9097
funded_at                   0.0000
raised_amount_usd          17.3903
permalink                   0.0000
name                        0.0009
homepage_url                5.3363
category_list               2.9665
status                      0.0000
country_code                7.5494
state_code                  9.5225
region                      8.8448
city                        8.8422
founded_at                 17.8523
dtype: float64

In [27]:
#As we have seen above that many columns contain large no. of null values so we can drop those columns that are 
#either of no use in future or the columns having the null values greater that 30%

In [28]:
master_frame1.drop(['funding_round_code','permalink','funding_round_permalink','funded_at','homepage_url','state_code','region',
                                'city','founded_at'],axis=1,inplace=True)

In [29]:
master_frame1.head(10)         #After dropping the above mentioned columns

,company_permalink,funding_round_type,raised_amount_usd,name,category_list,status,country_code
0,/organization/-fame,venture,10000000.0,#fame,Media,operating,IND
1,/organization/-qounter,venture,NaN,:Qounter,Application Platforms|Real Time|Social Network...,operating,USA
2,/organization/-qounter,seed,700000.0,:Qounter,Application Platforms|Real Time|Social Network...,operating,USA
3,/organization/-the-one-of-them-inc-,venture,3406878.0,"(THE) ONE of THEM,Inc.",Apps|Games|Mobile,operating,NaN
4,/organization/0-6-com,venture,2000000.0,0-6.com,Curated Web,operating,CHN
5,/organization/004-technologies,venture,NaN,004 Technologies,Software,operating,USA
6,/organization/01games-technology,undisclosed,41250.0,01Games Technology,Games,operating,HKG
7,/organization/0ndine-biomedical-inc,seed,43360.0,Ondine Biomedical Inc.,Biotechnology,operating,CAN
8,/organization/0ndine-biomedical-inc,venture,719491.0,Ondine Biomedical Inc.,Biotechnology,operating,CAN
9,/organization/0xdata,seed,3000000.0,H2O.ai,Analytics,operating,USA

In [30]:
len(master_frame1[master_frame1.isnull().sum(axis=1)>5]) #To find if any row contains more the 5 null values.

0

In [31]:
round(100*((master_frame1.isnull().sum())/(len(master_frame1))),4)

company_permalink      0.0000
funding_round_type     0.0000
raised_amount_usd     17.3903
name                   0.0009
category_list          2.9665
status                 0.0000
country_code           7.5494
dtype: float64

In [32]:
master_frame1['raised_amount_usd'].describe()

count    9.495900e+04
mean     1.042687e+07
std      1.148212e+08
min      0.000000e+00
25%      3.225000e+05
50%      1.680511e+06
75%      7.000000e+06
max      2.127194e+10
Name: raised_amount_usd, dtype: float64

In [33]:
master_frame1=master_frame1[~np.isnan(master_frame1['raised_amount_usd'])] #Here we extract those values of
                                                                           #master_frame1['raised_amount_usd']that are not null

In [34]:
round(100*((master_frame1.isnull().sum())/(len(master_frame1))),4)

company_permalink     0.0000
funding_round_type    0.0000
raised_amount_usd     0.0000
name                  0.0011
category_list         1.0994
status                0.0000
country_code          6.1616
dtype: float64

In [35]:
master_frame1['raised_amount_usd'].describe()

count    9.495900e+04
mean     1.042687e+07
std      1.148212e+08
min      0.000000e+00
25%      3.225000e+05
50%      1.680511e+06
75%      7.000000e+06
max      2.127194e+10
Name: raised_amount_usd, dtype: float64

In [36]:
master_frame1.drop(['status'],axis=1,inplace=True)

In [37]:
master_frame1.head(10)

,company_permalink,funding_round_type,raised_amount_usd,name,category_list,country_code
0,/organization/-fame,venture,10000000.0,#fame,Media,IND
2,/organization/-qounter,seed,700000.0,:Qounter,Application Platforms|Real Time|Social Network...,USA
3,/organization/-the-one-of-them-inc-,venture,3406878.0,"(THE) ONE of THEM,Inc.",Apps|Games|Mobile,NaN
4,/organization/0-6-com,venture,2000000.0,0-6.com,Curated Web,CHN
6,/organization/01games-technology,undisclosed,41250.0,01Games Technology,Games,HKG
7,/organization/0ndine-biomedical-inc,seed,43360.0,Ondine Biomedical Inc.,Biotechnology,CAN
8,/organization/0ndine-biomedical-inc,venture,719491.0,Ondine Biomedical Inc.,Biotechnology,CAN
9,/organization/0xdata,seed,3000000.0,H2O.ai,Analytics,USA
10,/organization/0xdata,venture,20000000.0,H2O.ai,Analytics,USA
11,/organization/0xdata,venture,1700000.0,H2O.ai,Analytics,USA

In [38]:
master_frame1.reset_index(drop='index',inplace=True)

In [39]:
master_frame1.head(10)

,company_permalink,funding_round_type,raised_amount_usd,name,category_list,country_code
0,/organization/-fame,venture,10000000.0,#fame,Media,IND
1,/organization/-qounter,seed,700000.0,:Qounter,Application Platforms|Real Time|Social Network...,USA
2,/organization/-the-one-of-them-inc-,venture,3406878.0,"(THE) ONE of THEM,Inc.",Apps|Games|Mobile,NaN
3,/organization/0-6-com,venture,2000000.0,0-6.com,Curated Web,CHN
4,/organization/01games-technology,undisclosed,41250.0,01Games Technology,Games,HKG
5,/organization/0ndine-biomedical-inc,seed,43360.0,Ondine Biomedical Inc.,Biotechnology,CAN
6,/organization/0ndine-biomedical-inc,venture,719491.0,Ondine Biomedical Inc.,Biotechnology,CAN
7,/organization/0xdata,seed,3000000.0,H2O.ai,Analytics,USA
8,/organization/0xdata,venture,20000000.0,H2O.ai,Analytics,USA
9,/organization/0xdata,venture,1700000.0,H2O.ai,Analytics,USA

In [40]:
round(100*((master_frame1.isnull().sum())/(len(master_frame1))),4)

company_permalink     0.0000
funding_round_type    0.0000
raised_amount_usd     0.0000
name                  0.0011
category_list         1.0994
country_code          6.1616
dtype: float64

In [41]:
master_frame1['country_code'].describe()

count     89108
unique      134
top         USA
freq      62049
Name: country_code, dtype: object

In [42]:
master_frame1['country_code'].value_counts()

USA    62049
GBR     5019
CAN     2616
CHN     1927
IND     1649
       ...
QAT        1
IRN        1
UZB        1
SYC        1
MNE        1
Name: country_code, Length: 134, dtype: int64

In [43]:
master_frame1=master_frame1[~master_frame1['country_code'].isnull()]#Here we extract those values of
                                                                     #master_frame1['country_code']that are not null

In [44]:
round(100*((master_frame1.isnull().sum())/(len(master_frame1))),4)

company_permalink     0.0000
funding_round_type    0.0000
raised_amount_usd     0.0000
name                  0.0011
category_list         0.6498
country_code          0.0000
dtype: float64

In [45]:
master_frame1=master_frame1[~master_frame1['category_list'].isnull()]#Here we extract those values of
                                                                     #master_frame1['category_list']that are not null

In [46]:
round(100*((master_frame1.isnull().sum())/(len(master_frame1))),4)

company_permalink     0.0000
funding_round_type    0.0000
raised_amount_usd     0.0000
name                  0.0011
category_list         0.0000
country_code          0.0000
dtype: float64

In [47]:
master_frame1=master_frame1[~master_frame1['name'].isnull()]#Here we extract those values of
                                                            #master_frame1['name']that are not null

In [48]:
round(100*((master_frame1.isnull().sum())/(len(master_frame1))),4)

company_permalink     0.0
funding_round_type    0.0
raised_amount_usd     0.0
name                  0.0
category_list         0.0
country_code          0.0
dtype: float64

In [49]:
#Now our data is clean.

In [50]:
master_frame1.to_csv(r'C:\Users\DELL\Desktop\data science training\master_frame.csv',index=False)

# Master Frame

In [51]:
master_frame=pd.read_csv(r'C:\Users\DELL\Desktop\data science training\master_frame.csv')

In [52]:
master_frame.head(10)

,company_permalink,funding_round_type,raised_amount_usd,name,category_list,country_code
0,/organization/-fame,venture,10000000.0,#fame,Media,IND
1,/organization/-qounter,seed,700000.0,:Qounter,Application Platforms|Real Time|Social Network...,USA
2,/organization/0-6-com,venture,2000000.0,0-6.com,Curated Web,CHN
3,/organization/01games-technology,undisclosed,41250.0,01Games Technology,Games,HKG
4,/organization/0ndine-biomedical-inc,seed,43360.0,Ondine Biomedical Inc.,Biotechnology,CAN
5,/organization/0ndine-biomedical-inc,venture,719491.0,Ondine Biomedical Inc.,Biotechnology,CAN
6,/organization/0xdata,seed,3000000.0,H2O.ai,Analytics,USA
7,/organization/0xdata,venture,20000000.0,H2O.ai,Analytics,USA
8,/organization/0xdata,venture,1700000.0,H2O.ai,Analytics,USA
9,/organization/0xdata,venture,8900000.0,H2O.ai,Analytics,USA

In [53]:
len(master_frame['company_permalink'].unique())

48729

In [54]:
master_frame.shape

(88528, 6)